spring.application.name=BeautySalon

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/salondb
spring.datasource.username=salon
spring.datasource.password=salon
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true

# JWT Configuration
app.jwt.secret=PPp27xSTfBwOpRn4/AV6gPzQSnQg+Oi80KdWfCcuAHs=
# test purpose 1min 60000  otherwise 15min 900000
app.jwt.access-token-expiration-ms=900000 
app.jwt.refresh-token-expiration-ms=604800000

# CORS Configuration
app.cors.allowed-origins=http://localhost:4200