spring.application.name=BeautySalon
spring.datasource.url=jdbc:postgresql://localhost:5432/salondb
spring.datasource.username=salon
spring.datasource.password=salon
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true